# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4defd83bf43a705414814ab78952b1dc3598ab40780b7cf7fbb9a5f3015e2d4c5b6a2737ce0c4a3f40a68a370549f401bc48798ad4243968be593aee1cfb6e43

test:
  secret_key_base: 50b917c916c72271f0e42817be1d674ee43fd01434cbf5e70b8a5410b39b1b75db1a98f9cf30ed5f22c7ddfdde98776e3f3f1034e71abcf2a678b681b9444d14

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
